// Prepares website/ for publishing: reads the built installers from release/, computes their SHA-256
// and writes website/downloads.js (+ SHA256SUMS.txt) that the download page reads.
//
//   npm run site:prepare                          self-hosted: copies the .exe files into website/downloads/
//   npm run site:prepare -- --base-url https://github.com/USER/REPO/releases/download/v1.0.0/
//                                                 hosted elsewhere (e.g. GitHub Releases): nothing is copied
//   npm run site:prepare -- --site-url https://f2px.example.com/
//                                                 also writes website/latest.json with that page as the "download" link.
//                                                 Put the address of latest.json into package.json ("f2px.updateFeed")
//                                                 and rebuild, and installed browsers will tell users about new versions.
const crypto = require('node:crypto')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const release = path.join(root, 'release')
const site = path.join(root, 'website')
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))

const args = process.argv.slice(2)
const baseIndex = args.indexOf('--base-url')
let baseUrl = baseIndex >= 0 ? args[baseIndex + 1] : ''
if (baseIndex >= 0 && !/^https?:\/\//.test(baseUrl || '')) {
  console.error('--base-url must be an http(s) URL, e.g. https://github.com/USER/REPO/releases/download/v' + pkg.version + '/')
  process.exit(1)
}
if (baseUrl && !baseUrl.endsWith('/')) baseUrl += '/'
const siteIndex = args.indexOf('--site-url')
const siteUrl = siteIndex >= 0 ? args[siteIndex + 1] : ''
if (siteIndex >= 0 && !/^https:\/\//.test(siteUrl || '')) {
  console.error('--site-url must be an https:// URL (the update notice only links to https pages), e.g. https://f2px.example.com/')
  process.exit(1)
}

const FILES = {
  setup: { name: 'F2PX-Browser-Setup.exe', label: 'Installer' },
  portable: { name: 'F2PX-Browser.exe', label: 'Portable' }
}

function sha256(file) {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash('sha256')
    fs.createReadStream(file).on('data', (d) => hash.update(d)).on('end', () => resolve(hash.digest('hex'))).on('error', reject)
  })
}

async function main() {
  fs.mkdirSync(path.join(site, 'downloads'), { recursive: true })
  const out = {}
  const sums = []
  for (const [key, { name }] of Object.entries(FILES)) {
    const src = path.join(release, name)
    if (!fs.existsSync(src)) {
      console.error(`Missing ${src}. Run "npm run dist" first.`)
      process.exit(1)
    }
    const stat = fs.statSync(src)
    const hash = await sha256(src)
    if (!baseUrl) fs.copyFileSync(src, path.join(site, 'downloads', name))
    out[key] = { name, url: baseUrl ? baseUrl + name : `downloads/${name}`, size: stat.size, sha256: hash }
    sums.push(`${hash}  ${name}`)
    console.log(`${name}  ${(stat.size / 1048576).toFixed(1)} MB  sha256 ${hash}`)
  }
  const data = { version: pkg.version, date: new Date().toISOString().slice(0, 10), files: out }
  fs.writeFileSync(path.join(site, 'downloads.js'), `// generated by scripts/prepare-site.cjs\nwindow.F2PX_DOWNLOADS = ${JSON.stringify(data, null, 2)}\n`)
  fs.writeFileSync(path.join(site, 'SHA256SUMS.txt'), sums.join('\n') + '\n')
  if (siteUrl) {
    const feed = { version: pkg.version, url: siteUrl, notes: '' }
    fs.writeFileSync(path.join(site, 'latest.json'), JSON.stringify(feed, null, 2) + '\n')
    console.log(`Update feed written to website/latest.json (set "f2px.updateFeed" in package.json to <site>/latest.json)`)
  }
  console.log(baseUrl ? `Links point to ${baseUrl}` : 'Installers copied to website/downloads/')
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
