// generated by scripts/prepare-site.cjs
window.F2PX_DOWNLOADS = {
  "version": "1.0.0",
  "date": "2026-09-20",
  "files": {
    "setup": {
      "name": "F2PX-Browser-Setup.exe",
      "url": "downloads/F2PX-Browser-Setup.exe",
      "size": 105197823,
      "sha256": "e54b656314d6799d72821121ba9665033a6a8fe479f6c02d8d1b75b41f88006a"
    },
    "portable": {
      "name": "F2PX-Browser.exe",
      "url": "downloads/F2PX-Browser.exe",
      "size": 105025889,
      "sha256": "f304bc765c73f97f536132861d48e5ddc1ab4293216513275cc81e637516f0e7"
    }
  }
}
